//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RegsForm
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Program { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public string Position { get; set; }
    }
}
